# Generated by Django 3.2.9 on 2021-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, max_length=2, verbose_name='Процент Скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_activated',
            field=models.BooleanField(default=False, verbose_name='Активировать скидку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Скидка'),
        ),
    ]
