# Generated by Django 3.2.9 on 2021-11-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211124_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='---', verbose_name='Описание'),
        ),
    ]
