# Generated by Django 3.2.9 on 2021-12-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211202_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, max_length=1, verbose_name='Процент cкидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_activated',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
    ]
