# Generated by Django 3.2.9 on 2021-11-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211124_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=99, verbose_name='Цена'),
        ),
    ]
