# Generated by Django 3.2.9 on 2021-11-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
