# Generated by Django 3.2.9 on 2021-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=99, verbose_name='Цена'),
        ),
    ]
